### PR TITLE
chore: node update

### PR DESCRIPTION
**Pull request by MarcoKorinth**
update node version in github actions

### CODE REVIEW

**Review by tschmidtb51 — CHANGES_REQUESTED** [review]
You mentioned that you also updated the documentation, but the README is unchanged...
It mentions at least one time Node 14.

**Comment by MarcoKorinth** [comment]
> You mentioned that you also updated the documentation, but the README is unchanged... It mentions at least one time Node 14.

Node 14 is mentioned in the context of mocha tests. The minimal supported Node version for that is still 14.
Updating that would be an incorrect statement, but if you want to remove that statement due to deprecation reasons I would propose the remove the sentence `The minimal supported Node.js version is **14**.` as a whole.

Other than that the README didn't mention any specific Node version so there was no need to update it.

**Review by tschmidtb51 — APPROVED** [review]
LGTM

**Review by tschmidtb51 — APPROVED** [review]
LGTM

**Pull request merged**
